### ISSUE TITLE
java.lang.NullPointerException (no error message)

### ISSUE THREAD

**Issue by logan62334** [app-bootstrap/android-app-bootstrap#13]
我clone到本地后，运行报下面的错误，没有具体信息
Execution failed for task ':android_app_bootstrap:transformNative_libsWithStripDebugSymbolForDebug'.
> java.lang.NullPointerException (no error message)

**Comment by xudafeng** [comment]
以ci为准，请检查环境 https://travis-ci.org/xudafeng/android-app-bootstrap
